---
driver:
  name: docker
  hostname: varnish.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: varnish
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - varnish
  pillars:
    top.sls:
      base:
        "*":
          - varnish
  dependencies:
    - name: leonardo
      repo: git
      source: https://github.com/salt-formulas/salt-formula-leonardo.git
verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'trevorj/salty-whales:xenial'%>
      platform: ubuntu

suites:

  - name: single
    provisioner:
      pillars-from-files:
        varnish.sls: tests/pillar/single.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
